#!/usr/bin/env python3
"""
Generates the integration's icon from the curve module itself: the icon
IS the day's brightness/colour curve. Bar heights come from
brightness_for_phase, bar colours from kelvin_for_phase through
kelvin_to_rgb, and the schedule is curve.py's DEFAULT_SCHEDULE_HOURS, so
changing the defaults and regenerating keeps them in step.

Writes brand/icon.svg (authoring only), the two PNGs Home Assistant
serves from the integration's own folder,
`custom_components/flare/brand/{icon.png,icon@2x.png}`, and the same
bars as a one-colour 24px glyph for the sidebar,
`custom_components/flare/www/flare-icon.js` (the `flare:logo` icon).

The PNGs are drawn with Pillow at 4x and downsampled, which keeps the
rounded corners clean and the background transparent without an SVG
rasteriser dependency. Don't render them with `qlmanage`: it composites
onto white.

Needs Pillow: `pip install pillow`.

Run from the repo root: python3 brand/generate_icon.py
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from custom_components.flare.schedule.curve import (  # noqa: E402
    DEFAULT_SCHEDULE_HOURS,
    brightness_for_phase,
    kelvin_for_phase,
    kelvin_to_rgb,
    phase_at,
)

SIZE = 256
CORNER_R = 58  # squircle-ish, matches typical brand-icon rounding
BG = "#171a26"  # deep night-blue, so both the warm and cool ends pop

# Chart area inside the tile.
PAD_X = 34
PAD_BOTTOM = 46
PAD_TOP = 56
CHART_W = SIZE - 2 * PAD_X
CHART_H = SIZE - PAD_TOP - PAD_BOTTOM

N_BARS = 7  # same bar language as the dashboard card, icon-sized

# A representative day (hours -> synthetic
# timestamps; the curve functions only care about differences).
MORNING = DEFAULT_SCHEDULE_HOURS["morning"] * 3600
DAY = DEFAULT_SCHEDULE_HOURS["day"] * 3600
EVENING = 18 * 3600  # a mid-window sunset, between earliest and latest
NIGHT = DEFAULT_SCHEDULE_HOURS["night"] * 3600

# Zoom the icon onto the interesting stretch of the day - from just
# before Morning to just after Night - rather than the full 24h, half
# of which is a flat night shelf that wastes icon real estate.
T_START = MORNING - 3 * 3600
T_END = NIGHT + 3 * 3600


BRAND_DIR = Path(__file__).resolve().parent.parent / "custom_components" / "flare" / "brand"
ICON_JS = BRAND_DIR.parent / "www" / "flare-icon.js"

# The glyph's box, MDI's, with this much clear on each side.
GLYPH_SIZE = 24
GLYPH_MARGIN = 1

# Drawn this many times larger and scaled back down. Pillow has no
# antialiasing of its own, so a rounded corner drawn at final size comes
# out visibly stepped; downsampling from 4x is what makes the tile's
# corners and the bars' caps smooth.
SUPERSAMPLE = 4


def y_of(brightness):
    return SIZE - PAD_BOTTOM - (brightness / 255) * CHART_H


def render_png(bars, size):
    """The same shapes the SVG describes, as pixels - on a TRANSPARENT
    background.

    That last part is the entire point of this function existing. The
    tile is a rounded rectangle, so the four corners outside it must be
    alpha 0; the thumbnailer this replaced composited them onto white,
    and Home Assistant drew the result as a white square behind the
    icon."""
    scale = size / SIZE * SUPERSAMPLE
    image = Image.new("RGBA", (int(SIZE * scale), int(SIZE * scale)), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    draw.rounded_rectangle(
        (0, 0, SIZE * scale - 1, SIZE * scale - 1),
        radius=CORNER_R * scale,
        fill=BG,
    )
    for x, y, w, h, radius, colour in bars:
        draw.rounded_rectangle(
            (x * scale, y * scale, (x + w) * scale - 1, (y + h) * scale - 1),
            radius=radius * scale,
            fill=colour,
        )

    return image.resize((size, size), Image.LANCZOS)


def glyph_path(bar_specs):
    """The bars as one SVG path in a 24px box, each a pill: what MDI icons
    are, so it sits beside them in the sidebar."""
    left = min(x for x, *_ in bar_specs)
    right = max(x + w for x, _, w, *_ in bar_specs)
    top = min(y for _, y, *_ in bar_specs)
    bottom = max(y + h for _, y, _, h, *_ in bar_specs)
    scale = (GLYPH_SIZE - 2 * GLYPH_MARGIN) / (right - left)
    offset_y = (GLYPH_SIZE - (bottom - top) * scale) / 2
    parts = []
    for x, y, w, h, _, _ in bar_specs:
        gx = (x - left) * scale + GLYPH_MARGIN
        gy = (y - top) * scale + offset_y
        gw, gh = w * scale, h * scale
        r = gw / 2
        parts.append(
            f"M{gx:.2f} {gy + r:.2f}a{r:.2f} {r:.2f} 0 0 1 {gw:.2f} 0"
            f"v{gh - gw:.2f}a{r:.2f} {r:.2f} 0 0 1 -{gw:.2f} 0z"
        )
    return "".join(parts)


def icon_js(path):
    return f"""/**
 * The `flare:logo` icon: FLARE's logo as a one-colour glyph, for the
 * dashboard's sidebar entry. Generated by brand/generate_icon.py.
 */

const PATH = '{path}';

window.customIcons = window.customIcons || {{}};
window.customIcons.flare = {{
  getIcon: async () => ({{ path: PATH, viewBox: '0 0 {GLYPH_SIZE} {GLYPH_SIZE}' }}),
  getIconList: async () => [{{ name: 'logo' }}],
}};
"""


def main():
    # One bar per sample across the zoomed window - the dashboard card's
    # bar language, at icon scale. Each bar's height is the real
    # brightness and its colour the real Kelvin at that instant; the
    # hard jump at Morning and the evening fade are what make this
    # schedule recognisably itself.
    slot_w = CHART_W / N_BARS
    bar_w = slot_w * 0.68
    baseline = SIZE - PAD_BOTTOM

    # Geometry once, rendered twice - as SVG below and as pixels in
    # render_png. Two hand-maintained copies of the same seven bars is
    # exactly how the icon and its source drift apart.
    bar_specs = []
    for i in range(N_BARS):
        t = T_START + (T_END - T_START) * (i + 0.5) / N_BARS
        phase = phase_at(t, MORNING, DAY, EVENING, NIGHT)
        # Both take (phase, now, morning, day, evening, night). Note
        # targets_for_phase in curve.py takes those four in a
        # DIFFERENT order - don't copy this call over to that one.
        b = brightness_for_phase(phase, t, MORNING, DAY, EVENING, NIGHT)
        colour = kelvin_to_rgb(kelvin_for_phase(phase, t, MORNING, DAY, EVENING, NIGHT))
        x = PAD_X + i * slot_w + (slot_w - bar_w) / 2
        h = baseline - y_of(b)
        bar_specs.append((x, baseline - h, bar_w, h, bar_w / 2, colour))

    bars = [
        f'<rect x="{x:.1f}" y="{y:.1f}" width="{w:.1f}" height="{h:.1f}" '
        f'rx="{r:.1f}" fill="rgb({c[0]},{c[1]},{c[2]})" />'
        for x, y, w, h, r, c in bar_specs
    ]

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}">
  <rect x="0" y="0" width="{SIZE}" height="{SIZE}" rx="{CORNER_R}" fill="{BG}" />
  {chr(10).join('  ' + b for b in bars).strip()}
</svg>
"""

    out_path = Path(__file__).resolve().parent / "icon.svg"
    out_path.write_text(svg)
    print(f"wrote {out_path}")

    ICON_JS.write_text(icon_js(glyph_path(bar_specs)))
    print(f"wrote {ICON_JS}")

    for size, name in ((SIZE, "icon.png"), (SIZE * 2, "icon@2x.png")):
        png_path = BRAND_DIR / name
        render_png(bar_specs, size).save(png_path)
        print(f"wrote {png_path}")


if __name__ == "__main__":
    main()
